
<section id="nav-page" class="mt-5">
    <div class="container">
        <div class="w-full bg-neutral-300 py-2 rounded-lg shadow-lg">
            <table class="table-nav">
                <tr>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/dashboard") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/dashboard/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/dashboard") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/dashboard/") ){echo "#";} else {echo BASE_URI."admin/dashboard/";} ?>">Dashboard</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/client") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/client/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/client") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/client/") ){echo "#";} else {echo BASE_URI."admin/client/";} ?>">Freelancer</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/user") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/user/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/user") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/user/") ){echo "#";} else {echo BASE_URI."admin/user/";} ?>">Admin</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/")){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/")){echo "#";} else {echo BASE_URI."admin/finance/";} ?>">Keuangan</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/setting") ||($_SERVER["REQUEST_URI"] === BASE_URI."admin/setting/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/setting") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/setting/") ){echo "#";} else {echo BASE_URI."admin/setting/";} ?>">Pengaturan</a></td>
                </tr>
            </table>
            <?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/")): ?>
            <table class="table-nav mt-2">
                <tr>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/")){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/")){echo "#";} else {echo BASE_URI."admin/finance/";} ?>">Konfirmasi Top Up</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/balance/") ){echo "#";} else {echo BASE_URI."admin/finance/balance/";} ?>">Tambah Saldo</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/history/") ){echo "#";} else {echo BASE_URI."admin/finance/history/";} ?>">Riwayat Transaksi</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/") ){echo "#";} else {echo BASE_URI."admin/finance/income/";} ?>">Pendapatan</a></td>
                </tr>
            </table>
            <?php endif ?>
        </div>
    </div>
</section>