
<section id="nav-page" class="mt-5">
    <div class="container">
        <div class="w-full bg-neutral-300 py-2 rounded-lg shadow-lg">
            <table class="table-nav">
                <tr>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/dashboard") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/dashboard/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/dashboard") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/dashboard/") ){echo "#";} else {echo BASE_URI."admin/dashboard/";} ?>">Dashboard</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/client") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/client/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/client") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/client/") ){echo "#";} else {echo BASE_URI."admin/client/";} ?>">Pengguna</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/user") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/user/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/user") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/user/") ){echo "#";} else {echo BASE_URI."admin/user/";} ?>">Admin</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/")){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill/")  || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/")){echo "#";} else {echo BASE_URI."admin/finance/";} ?>">Keuangan</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/site") ||($_SERVER["REQUEST_URI"] === BASE_URI."admin/site/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/site") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/site/") ){echo "#";} else {echo BASE_URI."admin/site/";} ?>">Situs</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/account") ||($_SERVER["REQUEST_URI"] === BASE_URI."admin/account/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/account") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/account/") ){echo "#";} else {echo BASE_URI."admin/account/";} ?>">Akun</a></td>
                </tr>
            </table>
            <?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/")  || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill/") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/")): ?>
            <table class="table-nav mt-2">
                <tr>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/")){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/")){echo "#";} else {echo BASE_URI."admin/finance/";} ?>">Riwayat Transaksi</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/bill/") ){echo "#";} else {echo BASE_URI."admin/finance/bill/";} ?>">Tagihan Pelanggan</a></td>
                    <td class="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/") ){echo "table-nav-td-active table-nav-td-spacing";} else {echo "table-nav-td-spacing table-nav-td";} ?>"><a href="<?php if(($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income") || ($_SERVER["REQUEST_URI"] === BASE_URI."admin/finance/income/") ){echo "#";} else {echo BASE_URI."admin/finance/income/";} ?>">Pendapatan</a></td>
                </tr>
            </table>
            <?php endif ?>
        </div>
    </div>
</section>